version: '3.8'

services:
  db:
    image: mysql:8.0.38
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: lojacorr123
      MYSQL_DATABASE: lojacorr
      MYSQL_PASSWORD: lojacorr123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lojacorr
      - DB_USERNAME=root
      - DB_PASSWORD=lojacorr123
    volumes:
        - ./app:/var/www/html/app
        - ./bootstrap:/var/www/html/bootstrap
        - ./config:/var/www/html/config
        - ./database:/var/www/html/database
        - ./node_modules:/var/www/html/node_modules
        - ./public:/var/www/html/public
        - ./resources:/var/www/html/resources
        - ./routes:/var/www/html/routes
        - ./storage:/var/www/html/storage
        - ./tests:/var/www/html/tests
        - ./vendor:/var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
